Simp 10737: make parameter $auditd::backlog_wait_time optional by adding $auditd::backlog_wait_time_enable
simp/pupmod-simp-auditd pull request #158
Opened 2022-07-29 15:10 UTC by befischer-noris

please refer to [SIMP-10737](https://simp-project.atlassian.net/browse/SIMP-10737) for more details

2022-07-29 21:17 UTC, trevor-vaughan requested changes
@befischer-noris Thanks for the update!

Ideally, we would determine what version of `auditd` has the breakage and only enable the parameter when appropriate using the `auditd_version` fact.

2022-08-02 09:59 UTC, befischer-noris commented
Hi @trevor-vaughan, 
I definitely agree with adding checks. But in this case it's not possible.

'--backlog_wait_time' was introduced in [acc726fd44ca8305d9f9f8cd71ca4fac805275de Add support for backlog_time_wait setting via auditctl](https://github.com/linux-audit/audit-userspace/commit/acc726fd44ca8305d9f9f8cd71ca4fac805275de) and was released in version [2.4.1](https://github.com/linux-audit/audit-userspace/commit/e8884928a0154f17dec8d05fd2785ca7293189bc) till then this rule exists in auditd. 

Since then this rule can be used in the package. [Only when](https://github.com/linux-audit/audit-userspace/blob/master/configure.ac#L67) the specific parameter 'AUDIT_VERSION_BACKLOG_WAIT_TIME' is set to 0 the [rule is not added to the package](https://github.com/linux-audit/audit-userspace/blob/master/src/auditctl.c#L141).

Therefore I'd suggest not adding an additional check and leaving it as it is. Especially since it has no impact for other users  / upgrade from older versions.

2022-08-14 21:36 UTC, trevor-vaughan commented
@befischer-noris Well, that's unfortunate, but you're right. I suppose we'll have to leave it up to the user to define so the existing implementation looks good to me.

2022-08-14 21:40 UTC, trevor-vaughan requested changes
@befischer-noris Given that we have to leave this up to the user and we're simply setting the default value to the built-in value I would like to propose that instead of adding an additional parameter, we simply make the `backlog_wait_time` parameter `Optional` and set it to `undef` by default. The tests will probably need some updates but I think that this will be the cleanest implementation.

Sorry for the churn, I hadn't realized that it was a compilation issue.

2022-08-22 22:02 UTC, trevor-vaughan approved these changes

2022-08-24 21:27 UTC, merged